[font]
normal = { family = "JetBrainsMonoNerdFont", style="Regular"}
bold = {family = "JetBrainsMonoNerdFont", style="Bold"}
italic = {family= "JetBrainsMonoNerdFont", style="Italic"}
size = 11.5

[window]
padding = { x = 0, y = 0}
dynamic_padding = true
decorations = "None"

[colors.primary]
background="#202020"
